apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mailu-secret
  namespace: mailu
spec:
  encryptedData:
    secret_key: AgB5Iauyl+NykOH/Zl+Ygge5yIzs6+xEWKV6rIzOITpmJVoYvGpRFZZ/GVvosmZMG3WlZ6GcTfk3Ubsa6lqJ0vYRjB+Lv0eiLPjQAcTiGa3xNzqOqIws6WyJX9azSIhXMV1gyvhfMcsGXuYpliY6V54JDcq0PzhadDuIubqrf5yGLWZLDQ2cihg3H5Fa+e4EMjKkst9wGgOAsJ0jki4fzLQrAsl/M68gtmlJWuzh8rWmMdpIIr9jpPR9RrX12RP0qPRUWayW6HuNx0bUNHM9H9ank+aYN3Srs+kkjeAd50KLQFbg85pycc4FJ9IZT7ysP+PwE58VWI1Dky9dKx0ALqx5asvxJPIZBQbiMg4b0PLAnmFMYYuQY60BQKsNIiadKjNhT4HmaTnzMY8I5UjRkjpcz+4aC8eJNBi3rW6xnw0/aFXc6qrIy6PyLqbhJvPE8cR/GzOv8+TYXWz0Jo4OwWRMIeuOEviQO1cDh7/TrviQox8mIIATymkxDVdcO4B9ZlrO+ARyum5/ouK3Yms2MZ+McsbgFgjV2nro8Whoy1WO3SoGwsdwQi6hlQ8GPavM6/HDK4ItohegGHnnEyPzegtFCYsWdLzNKDNaGNqiTo989zNs49xFOdyBoi8MDQzhFmw5qwDBXzGyvOBPoOpYuqwrJsphsPxXgDI+QxkWwu892CK32hExAv9RDfuZkL9JQ9T2XEzRA60o+DQtrvbXmqroCql+xE3Z1Sd4nQG5oOek62Qw4MeLwdEj
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mailu-secret
      namespace: mailu

