apiVersion: v1
kind: ConfigMap
metadata:
  name: pgrok
  namespace: tunnel
data:
  # generating all the things: https://gist.github.com/fntlnz/cf14feb5a46b2eda428e000157447309
  ca: |
    -----BEGIN CERTIFICATE-----
    MIIFVTCCAz2gAwIBAgIUdHsSUvGCpq9ASmil84AB4RatlpUwDQYJKoZIhvcNAQEL
    BQAwOjELMAkGA1UEBhMCREUxEzARBgNVBAgMClNvbWUtU3RhdGUxFjAUBgNVBAoM
    DWplbWFuZDc3MS5uZXQwHhcNMjIwMTE5MjEyMDA2WhcNMjQxMTA4MjEyMDA2WjA6
    MQswCQYDVQQGEwJERTETMBEGA1UECAwKU29tZS1TdGF0ZTEWMBQGA1UECgwNamVt
    YW5kNzcxLm5ldDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAOJjjLQF
    BzlL5frt+W7F9wH4Q5G7WmwMGKbR1kP8ZW3NULhgiZccOCY8ennK7cenqU4WT8ug
    F5UYCQl/Pi27SUO1TJ2ETpfoYBJhAwsQOrzSCDDB1fYx9btTZdqIHiHUD/P/hqIK
    y1bfnqrhGZq+BEpqGv169rK0Gy2+SzGNPUEwUyqBI1LRhd8ZXrkjeHDo7gAoMegV
    4XcyaDAIYadOEY5en4AFQtp0FL/eBzBNjY0oYWMUfu5k9VJoWOq/ezuPLYvVVVeL
    sXsVKBWhceuv7xHhnwTyVcr4fccQMGXaKH4o6g0HGtTMA2+ryTlNgppz8twxyZww
    uPAkNEXx6xEC/HYucZMJTWEQOVHECUL6Eiv8LxMOqUeld1R4pNg08j+Hpjr2upQU
    tMcEUmtU3WB7/C8E/uYlZkOJ6rhCHgb+snD4yPsw15hW1b//Wldh+RVpot9QWdc6
    Pw4nTbpYbaey7cJOWHsR2iPRvJlx8LbiMSViWziGAA8CdY1auzPZLW5R1yoFaigD
    g5U4ZtiEHP29NxEkYivT8gw2lPlJq1YjqVejq/gcaPaUFgKxYWf3b1ZPLDGrzjNh
    ouRJPKwBc1wwvGIGm+4YjCRupC/6UJjkV9INvh0Pg6ucgiPUDXBcgWDbAxQTYG9b
    xnV2ZJBxbpnkkx7ZFIW3xRowheIkJWmuhA5dAgMBAAGjUzBRMB0GA1UdDgQWBBT6
    8UkiJa9Z1s+QY9ntoWGW60XQhDAfBgNVHSMEGDAWgBT68UkiJa9Z1s+QY9ntoWGW
    60XQhDAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4ICAQBikCYayAOc
    WgRwV/LDhcBTZOmD5ZeGOXtZhx6b1522r/AOurtjn+DWUyuXUHl+IZCmTCj0iHRG
    LKP7acimj3zF2oJHtPa0gvXvQ3gIeJZy20ePqxjqWnaoy/n7R+kbmKK4/mGEk+yu
    T95eHwAQ9ZR3oTz13TmtBrw1eJcKBHR6rFhkdZjvvcbkCc5Ol6ul14Lu/ErE9yCQ
    eXfGDVkGDXLP3YEvkkopnvl/gbQaNoYGdPjaL+y7ujHGzT1GMnnhmvPybmZs27ee
    wkw9KqUev+WtMVk/0I3LvdPNPE8R+GHOdSOUiRU8zOzTE5UTLhdX5p5h+n5w0mod
    9bN9cuE7D1VgSM7GiEAWx44JIzLpgBsobbSKG7CmqCKskY3DmimXV1m3BbR53+Zn
    gysPBnKlS8sDtfQ8Ffe376y3wUFl3Iox9eZshoNmPgOsQ2E1WfqxPlO4yOwlWauO
    714a2ndUg+7SzPgR1hZbQq9inHdZ8uqjxGQdl4uoXXyQv97TFEDbPtlgD5FvzGCN
    PQDkuo8YH/SGAM5bq0PzYOXOa1lkyePqp+uzgZCxsL4RUqMpmDwa624kGIqyYx4J
    iZaDmVtOZ+XB2r9ek5cN+TO1A/YyUqRlO1zKl/n9RL1H/Zg+Irbi3le5f8da2+iG
    n0HYdnzju8MCVRRuRds9Cq4EiMfLOeR5ew==
    -----END CERTIFICATE-----
