apiVersion: v1
kind: Service
metadata:
  name: pgrok-http
  namespace: tunnel
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: pgrok
---
apiVersion: v1
kind: Service
metadata:
  name: pgrok
  namespace: tunnel
  annotations:
    metallb.universe.tf/allow-shared-ip: ipv4s-are-expensive
spec:
  type: LoadBalancer
  ports:
    - name: tunnel
      port: 32443
      targetPort: tunnel
  selector:
    app: pgrok
