apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-infra
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - name: in-cluster
      namespace: '*'
      server: 'https://kubernetes.default.svc'
  orphanedResources:
    ignore:
      - kind: ConfigMap
        name: argocd-cm
      - kind: Secret
        name: argocd-initial-admin-secret
        # no clue what this is, but it's here and I'm too scared to touch it
      - kind: Secret
        name: repo-1311690692
    warn: true
  sourceRepos:
    - '*'
