apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{name}"
spec:
  secretName: cert-key-{name}
  issuerRef:
    name: lets-encrypt
    kind: ClusterIssuer
  dnsNames:
    - {zone}
{dns_names}
