apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{name}"
  namespace: cert-manager
spec:
  secretName: cert-key-{name}
  issuerRef:
    name: cf-issuer
    kind: ClusterIssuer
  dnsNames:
    - {zone}
{dns_names}
