loki:
  storage:
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    type: s3
    s3:
      endpoint: cdn.jemand771.net
      region: us-east-1
      secretAccessKey: ${MINIO_ACCESS_SECRET}
      accessKeyId: ${MINIO_ACCESS_KEY}
      s3ForcePathStyle: true
      insecure: false
  server:
    log_level: warn
  # TODO auth? technically don't need it, but would be cool
  auth_enabled: false
backend:
  extraArgs:
    - -config.expand-env=true
  affinity: { }
  extraEnvFrom:
    - secretRef:
        name: loki-minio
read:
  extraArgs:
    - -config.expand-env=true
  affinity: { }
  extraEnvFrom:
    - secretRef:
        name: loki-minio
write:
  extraArgs:
    - -config.expand-env=true
  affinity: { }
  extraEnvFrom:
    - secretRef:
        name: loki-minio
tableManager:
  enabled: true
  extraArgs:
    - -config.expand-env=true
  affinity: { }
  extraEnvFrom:
    - secretRef:
        name: loki-minio
  retention_deletes_enabled: true
  retention_period: 168h
compactor:
  enabled: true
  extraArgs:
    - -config.expand-env=true
  affinity: { }
  extraEnvFrom:
    - secretRef:
        name: loki-minio
  retention_deletes_enabled: true
  retention_period: 168h
monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
test:
  enabled: false
