storage:
  trace:
    backend: s3
    s3:
      bucket: tempo-traces
      endpoint: cdn.jemand771.net
      region: us-east-1
      access_key: ${MINIO_ACCESS_KEY}
      secret_key: ${MINIO_ACCESS_SECRET}
      forcepathstyle: true
  admin:
    backend: s3
    s3:
      bucket: tempo-admin
      endpoint: cdn.jemand771.net
      region: us-east-1
      access_key: ${MINIO_ACCESS_KEY}
      secret_key: ${MINIO_ACCESS_SECRET}
      forcepathstyle: true
# the docs say I can use global.extraEnvFrom, but that didn't work for me :(
ingester:
  extraArgs:
    - -config.expand-env=true
  extraEnvFrom:
    - secretRef:
        name: loki-minio
distributor:
  extraArgs:
    - -config.expand-env=true
  extraEnvFrom:
    - secretRef:
        name: loki-minio
compactor:
  extraArgs:
    - -config.expand-env=true
  extraEnvFrom:
    - secretRef:
        name: loki-minio
querier:
  extraArgs:
    - -config.expand-env=true
  extraEnvFrom:
    - secretRef:
        name: loki-minio
queryFrontend:
  extraArgs:
    - -config.expand-env=true
  extraEnvFrom:
    - secretRef:
        name: loki-minio
