storage:
  trace:
    backend: s3
    s3:
      bucket: tempo-traces
      endpoint: cdn.jemand771.net
      region: us-east-1
      access_key: ${MINIO_ACCESS_KEY}
      secret_key: ${MINIO_ACCESS_SECRET}
      forcepathstyle: true
  admin:
    backend: s3
    s3:
      bucket: tempo-admin
      endpoint: cdn.jemand771.net
      region: us-east-1
      access_key: ${MINIO_ACCESS_KEY}
      secret_key: ${MINIO_ACCESS_SECRET}
      forcepathstyle: true
traces:
  otlp:
    http:
      enabled: true
    grpc:
      enabled: true
global_overrides:
  max_bytes_per_trace: 50000000  # 50MB, default is 5MB
# the docs say I can use global.extraEnvFrom, but that didn't work for me :(
ingester:
  extraArgs:
    - -config.expand-env=true
  extraEnvFrom:
    - secretRef:
        name: tempo-minio
distributor:
  affinity: {}
  extraArgs:
    - -config.expand-env=true
  extraEnvFrom:
    - secretRef:
        name: tempo-minio
compactor:
  extraArgs:
    - -config.expand-env=true
  extraEnvFrom:
    - secretRef:
        name: tempo-minio
querier:
  extraArgs:
    - -config.expand-env=true
  extraEnvFrom:
    - secretRef:
        name: tempo-minio
queryFrontend:
  extraArgs:
    - -config.expand-env=true
  extraEnvFrom:
    - secretRef:
        name: tempo-minio
