apiVersion: v1
kind: Service
metadata:
  name: asset-gen-api
  namespace: asset-gen-api
  labels:
    app: asset-gen-api
spec:
  selector:
    app: asset-gen-api
  ports:
    - port: 80
      targetPort: web
      name: web
