apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-test
  namespace: authentik
  labels:
    app: auth-test
spec:
  selector:
    matchLabels:
      app: auth-test
  template:
    metadata:
      labels:
        app: auth-test
    spec:
      containers:
        - name: auth-test
          image: containous/whoami
          ports:
            - containerPort: 80
              name: web
---
apiVersion: v1
kind: Service
metadata:
  name: auth-test
  namespace: authentik
spec:
  selector:
    app: auth-test
  ports:
    - port: 80
      name: web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-test
  namespace: authentik
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: authentik-authentik@kubernetescrd
spec:
  rules:
    - host: auth-test.771.blue
      http:
        paths:
          - backend:
              service:
                name: auth-test
                port:
                  name: web
            pathType: Prefix
            path: /
