resources:
  - authenik-ns.yaml
  - authentik-secret.yaml
  - authentik-traefik-middleware.yaml
  - auth-test.yaml
  - ratelimit.yaml
helmCharts:
  - name: authentik
    repo: https://charts.goauthentik.io/
    releaseName: authentik
    version: 2023.5.4
    namespace: authentik
    valuesFile: values.yaml
