apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: reloader
  namespace: reloader
spec:
  targetNamespace: reloader
  chart: reloader
  repo: https://stakater.github.io/stakater-charts
  version: v0.0.110
