apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hetzner-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-key: AgA5kLQ1m4bQuazNLkhtvySq8qd5+jBaci3+7NehAWdcN1yQfhvhggatt+lZnrIi67llbWqCBAgYTCE7GA0RcHxzQI9H/I0wj35TZKZhsm55o1LbjTgKJe1zVq7YizKotPXb9YASyuMMbEGWNXunVkkdYIQAN1Z24MTHYpH2h+MjPSquXRmQE61xRbXRWR8SmbIgCss+j6LS0bUgna+A/23zJixtmh18qbLk/fzDLx3ATVbir18Twx4H2u/YDhxXHPMVXnSpq+h857zsiKbrHIA3iCQp1pDIiXDzH9XbSNDJhXQKucSoSTXHCXf/nk19elVxzyVZpkLd/da8d5CL7ts99YT2aZsVjCvDs/hplH6AChkrBNWzcgKPy/dUlsTdjQ4MoxkYcw6sEQDHnN5ERfaookHM6h1XSNbwFr8tMUkOglf0suMXrmFJAVYK20k4BHu9aKatRWO34pNgOyKaA7hprufXuTZhZWcalSAnWAZpb2MICAK7k1bhhjjDARTOjSb/ORLTjetBUkJheCKdi1W7IB8nxbEDaTxLRxfTHNb99rCUzsPjWNVOpgmI++vUt7VEM+g7xrsXHyK93qUCyFC8Dd5nluV10nhOMVGkS3v/rnq/TI3e4m+T0VdhVEZgN60f+9zT4wsTLzB+g8xQctikqgGfE5b/+ku6f3XGwP3Z4joMrrp7ZnvTr+x0aq7KL4uBAt91wNEzfSWqZneHsEcSiLuu2hGwE1+XH0kdTzOGgQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: hetzner-secret
      namespace: cert-manager
    type: Opaque

