apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: obs-secret
  namespace: default
spec:
  encryptedData:
    vnc_password: AgBJ6as7xAwxvQc22azN7M/pEJBDKyjXskjHA1tLfh3zz2seJXVCCGTS7yTaT5xc4ho8bTYPguPFAe7ZfMjq2N/3ixtOBBCC1mY4cZvQNpK8dkQlKAG8xVt6T3amhVsgruoGcEZPmAlk4+ZZnXwbtxuZKCMeBtsAHHJ9V4RQswhmgiVnQs3lL2wUC3Vlip2iUMwSu5aYc+DMM2W3mAG92+EIyY9ux1PpONUBItHxHNGn5XKpcPJ28HZGfZS6FUZXcc2ZRD34xdM1Tf0T7oNABs9oQkc+U1EYn53MrKuug37zhEGA0y2ZkQeh0fvU73jSxWW3M1zDYdZkwUprXOKRg5KjQ+iDB1WTWJWIsv3DlRaVREe1MD7X1ZkvLtjOxKq8KHJnSbqd6m2165jzIh6VoyMQU+/kVOh94NixV6BHkvgZBiKcV1WWDHmtPU6oVdCpLVnOIK/xLcLZGsyHX2Pf9zAc/MV5Bcxp4knY46edfDNORbBINOuVuK54sRUP9MjEQ97y6mBkRPrs8JippyD9l/Xen7cFgCDc+4jpMesSG6cxEZLF4IL2Cun2HEg5zjJU0ArqpFddo0e5J0A9qtCMFjknNx2kTZS9iYhycoPHYkw0lhRz+dchsKiMdtVDgeraA/MrQao+YLNjQA8CybxM3ABXcctBraKbr7v8D0Zq4PFQqaUfdEIkKzpk3pH8kOl+5yBNPvtmODMHT71Pn3A=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: obs-secret
      namespace: default

