apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: obs-secret
  namespace: default
spec:
  encryptedData:
    vnc_password: AgCqYtET9ewFoUm83/SsPt+f+XS3rg1HQs06AYLrI0yRi2Hzwx1ZqQP8aPKiwNxuCT7SPvN7ya+Him/l2yB3l6p5NvlHNk30TCp6p6xHIFFPlQvI4ATyeCl+Do0jV8JjP0rLoYHelUJuexXXmB7YKvNkhchsPtBXeUwjAXl5wZCrcy09k3nShyJQwBfYCyK4+OvS095h7dHlU/lwCcarTvsS65gkjN1BDOY0+vNUKwHgyIuogq/WpKn4tefKk4rTISH9xWxXJ+xfZ+vuEGs9JyjkQq4sMNjWaAgrzZH6iOCHCAeP0QTAHzkRko4pIzi9txRcjX/YuBw3rPQPd5DGf+1dB2RWW3KZ3vUaZ+LDPmNAAOQ2m0/bX3U/c69dNwV7K/aqYXPa2SLyQoi3oeF+Z64+98a8KRDKn5nufH5j6X5NsFNJ7KT8jk7Wyo+kzVqrbrc3PIatg8qzfUkIzm6EAZ553AwA1W9UTPqUApQqVtD715VCOZtRRT8kCp9D3UCEFwiHI75EkZqIdRQRbTTQ0CtSMsCFbxBbn3rXPBCZAYSVo0dIIODHBeGD1bGS0vqqYSqD8ecvmSFoJmaiD0LhZBtp2pn1MrjO/psspreYn8bMmKZPauvFXzU7+RYGq07xSADsxpjRGY0hhEWYxHbhedeI1FYnspOtgv8mX4wvfS1ZaBzgTFP4RJjs24nho8vjLg4QoNm3/gVsbBvfkN4=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: obs-secret
      namespace: default

