apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: factorio-secrets
  namespace: factorio-skji
spec:
  encryptedData:
    RCON_PASSWORD: AgCZHltC8c7L1BXrLzskjvMIBdFgDLQi+wvbMTrK0zludG53prHU75Sp7ViGgU8Une48PHV64xr7WU3TFweCxhlI0khHruUCnSmlJ0g5Xe+T3kOaSKw2lfQqWOU+I/iAQ+IyiYpConCyHdmYpfX/S1kR9g38Dtw4mbnqUjxiqZ1YZ5sZim6LsDlo5+Uhc/BDBdq7k6iU4eOKjbMQOBUL8t5FkT+IJr5Yo1uf7CdEdHX4HUucK53INNyTMZv30DHemdrIPAEmO8MtxrxSjLNfqYNhSvfpN7uVRcoG8zdCwIBC08IzvMbVDQDniyZdA32pe+XRc1vkCFLlwWQlZKu9RZWZadKjFp0volFq2wcqzqPooZBXvLkL4JvZcqKSkhYsennNc4Bx5iufOvkKkGt20gsAxrADPTDCZ2kSIlvwTtlmUGx2Wdy3SQG2nc261Yhv9qSkUiEyMjGW9FxgUf0DRWVIcIKuWq1cUNE6fNRo/fqiNNiR+/SDpWkabxL/0SxVAXlzXKnY5linJhwPh1ca26/Hpj7ATolERO5YjRbBK+5PEyVPYVvrWdQZkt+iJY2yxjPTTh6K2B704ZdzmgyhkliSU+RwkUfPRvzzaGIc15VeQkkPM7oEgmp1cidfDiX0uKrNYwCQoac++NVKqXdgL3IUHCgXkrUYfAjTl9esGHiyjJ2dWk8cJDhP4MpZqZ6OqU4eHlOKBTSJjzNhUydbL84=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: factorio-secrets
      namespace: factorio-skji

