apiVersion: v1
kind: Service
metadata:
  name: factorio-game
  namespace: factorio-skji
spec:
  type: LoadBalancer
  selector:
    app: factorio
  ports:
    - port: 34197
      protocol: UDP
      name: factorio
      targetPort: factorio
