apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: meili-config
  namespace: meilisearch-test
spec:
  encryptedData:
    MEILI_MASTER_KEY: AgC54wBKAUiFdGzZ5TKoXTCPYDqZtITMULl/HMiNsk3TevxnW6meqpDG0+342w2iUFnFGld2ajS+HqAEDjAxKrmRKZiGmVRODc/EAOQU3ZpnnGN7j0MyAeDPjo6pfrCKZSSvrWFf1ZPTqDmvUNxfdxBumnY9I+0EXMeM9eK0eEDQdWwUzIWEhbJjNn+h1ZtNlK1HXdl7qRpJjtsx+o5ueS5n/RojplmVAAmH90fR5WLxFkv9X5V+LN/HgMBaffq4x8IrIn9pVbebj8ReVeCZ1UFpocSj79s/OiGjUrJg/om5dZQOs20+oA6Pqw07oqF5rwI/P3rSHyNpWQbcvrsdw28l4sNgjhb5bMatFt8sX/xAimuhVsTD+KsvS7WJWVgMuWkCwdui86E6qO8S/VilVVw9a+ok/rZYA9cpLxv/YYxd3y6+YGkoDKStHdB0VwapISjDlcN+tYSKMMTKhBnuVfUSPaFCL8eu/yOWr+bqGiF8HPuZEoc07quzvUW+IANoPhc2sGsjfldmo123hjIXbwMhbBGsZgholjY92+8wfgkUsBX3a+nMUqcwr0c51B7Yt3W0r1EcQvepVnKuwhmQ93BsVbnoniqZhcBSZ3/FmpdgRhFo4+JwWDQ68JYbZBrbOwJLG/Hj2Y8WJ97LAXYEPC8kMheMyOzrkDappsHZnyrDX6thOmFgd7rRpRRgQ064SdXVLEDacJgnhoos9nwWbWcz
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: meili-config
      namespace: meilisearch-test

