apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  template:
    spec:
      containers:
        - name: external-dns
          env:
            - name: EXTERNAL_DNS_PROVIDER
              value: cloudflare
            - name: EXTERNAL_DNS_TXT_PREFIX
              value: __external-dns-
          envFrom:
            - secretRef:
                name: cloudflare-token

