apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calico
  namespace: argocd
spec:
  destination:
    namespace: calico-system
    server: https://kubernetes.default.svc
  project: cluster-infra
  source:
    path: _infrastructure/calico
    repoURL: https://github.com/jemand771/server-deployments.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
