apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catzip
  namespace: argocd
spec:
  destination:
    namespace: catzip
    server: https://kubernetes.default.svc
  project: default
  source:
    path: catzip
    repoURL: https://github.com/jemand771/server-deployments.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
