apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fail2ban
  namespace: argocd
spec:
  destination:
    namespace: fail2ban
    server: https://kubernetes.default.svc
  project: cluster-infra
  source:
    path: _infrastructure/fail2ban
    repoURL: https://github.com/jemand771/server-deployments.git
    targetRevision: HEAD
