apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mc-plan
  namespace: argocd
spec:
  destination:
    namespace: mc-plan
    server: https://kubernetes.default.svc
  project: mc-infra
  source:
    path: minecraft/mc-plan
    repoURL: https://github.com/jemand771/server-deployments.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
