apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mc-smp5-staging
  namespace: argocd
spec:
  destination:
    namespace: smp5
    server: https://kubernetes.default.svc
  project: default
  source:
    path: minecraft/smp5-staging
    repoURL: https://github.com/jemand771/server-deployments.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
