apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuma
  namespace: kuma
  labels:
    app: kuma
spec:
  selector:
    matchLabels:
      app: kuma
  template:
    metadata:
      labels:
        app: kuma
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: 'true'
        prometheus.io/port: '3001'
    spec:
      containers:
        - name: kuma
          image: louislam/uptime-kuma:1.13.1
          ports:
            - containerPort: 3001
              name: web
          volumeMounts:
            - mountPath: /app/data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: kuma
      # this is VERY hacky.
      # I couldn't figure out how to do NAT reflection or hairpinning,
      # so this has to do for now.
      # This might be solvable by getting an extra ipv4 for the k8s vm
      hostAliases:
        - ip: 10.10.10.31
          hostnames:
            - minio.jemand771.net
            - sso.jemand771.net
            - jemand771.net