apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hetzner-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-key: AgDCdt8G+NegZRsXVWxS0PhKpLgc6gD2N68AM2LbYs/tr9EQaSyBQ2uPrLxu/VcocZRdFcdQ0sqOMj3hDyucSJfpYVY6SlYKQlXOUdudRGLU1HbTwKSJisJImygI/anfj61ZlEjjjKRO6eki2LE3txq01n4pKq7sllgDPe2WLlKPT2VBwFLFZAQnTy0qUpBqNqrMD0MPL97cnqQhtoOhr3YDFr16rCUHcF3zCaRqNlF+lUd+mOCZTNRU20dGptp2CVk7T0eF4b4OFLfcGN7wzCf7cWnQZFJtZTfa+m4SMm7IsBeda3mtv0KCl+9bAoqts+WJ6WSV2sEY+szRk4l7YAGueHNacKzmPviT9Kg39d2xArVBbzFatX03dzxPCD16mmnQpEbMdpWBUGDx4VfZ914CMN/lgkAqs1iWWXAyUICR3mbhcOk9GM8eZpaLBLW4FSHpAoadWhNIiDFSdd4+C0YgsIIQna27ggUDLmSeaDUlhyQL3oPhmLsWzo1wCMa5ZLhbdOdkM9m9zHV6kuyEs2vPd4GxZeWDkzZmbhSXzdDsIgePG1PASlvQ+tfTZvqrntFsnBnyT9jhXcqeDCHFGPonzZoJsZmeAV5//c4Ic5uRj2g/84rt1OBarqKGFdVE9Zn79lJ8EXDJj0AictWOsH8w3vxvPKhAut/f/cp2WSNS4kwHQLVF7qdM/4XnSB96snIku+hYjzcgpiKWu5tZyBAoJ+BIbpV3NGRp3TMEFcEUoQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: hetzner-secret
      namespace: cert-manager
    type: Opaque

