apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-upgrade-controller
  namespace: argocd
spec:
  destination:
    namespace: system-upgrade
    server: https://kubernetes.default.svc
  project: cluster-infra
  source:
    path: _infrastructure/k3s/system-upgrade-controller
    repoURL: https://github.com/jemand771/server-deployments.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
