apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: minio
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgC+pg+nD/JQCoJd4eweHtniaEk1hc2MwTzeMDrVaJP9RR0K97C9VldWeGYKDi5ioBa6a8bPF2eKtmdPuMPjYiTIrVP+UmApxa71YhyVPtv7USM4oVFZBUpd2rZgAIQOxf0MU1j9hKy8svwNz14YhCCr5syy48zkLSIkx7KQrkxnEnEllojgIVcypREKNDyVVtk1tyzFOhffqgDVqM5NCld+KCtHq5r3iwympWfM6f1MgVChY1eApw3Mbm/+JdtphuP1He40LPnS46xij/GwpmuXPb5j1uiyTxM/7dcMvtVWwgcygn3xiUEkRWOucYcY6w4D9S2GEAzlw2Y8DK4J4wkyaZrCdsg3rRKlSay/LmQTJtEysZNVuoOEIp2VejV0VEBpmp/MjyRvaQ2/qApRNFKYzNpxG7OF7jza9ZneJ6sdiEbo9H3NlyCZdjJd3AM6zW9QtJNurKoIKb8x7NgaAsUCFbc/d45Sg9vSqQSqtMSsswY5KpJ/vTqWyIXtZdUHkgzdgsuNS5suuyCIydMqlWMHihYhD7Nve3N4z+S8WozcnIc8Ws1/5ixZULH3UycYKt9AF11HV4Qu0IICgeX4NnVnAOMWgZtNb1qZz9cNKsoQDCIVJety1+I0THmWeDAZBx60dG3/xXdF3W7eG189e2ztfGLejg0xUbpH4ngxwf/RLD+kZYNq7sOsH4TI/oWp0ZLIZvKxvR0skxQLmy4qfyYNecBRRd9UYNc4XO35BEa56ocOP3n5FlTgA9DmWmwOjCi35VyBx2x47+2adFuO4k77
    MINIO_ROOT_USER: AgANFc2o/LIsdB8R8hgOe5/F7kBSrvUEy60JHvydhItOWvuOaFOGsRupLVKei6cbx10WxdGjMFL3upffQW0waYoF1wCcn0/FluI7vHg839lKarqlgEpL1ocoH/0zjlC4XEQS6nJjbGLCTMjrkYB8bq0GXJw2RwHBL48vs3kh0OIdUfaPE410P0N7jZgL3kSiNVGh1HS2Vc9+d4+t1dDTLNy1SNBSX7386/FQ2kLVWu9MkG4HPJlpqakRV6S1Pldb7ydH43PGexpWbUAu4ZMEop6g++PcmXuwLPGJgVsHwxGpl+QBHb+dGP8FJJjksZnhJ0EwEkF3o3RZZMqGI9KqyupZJ+t0z0hLw1SwDC2ZVspkWXXVx/zUafrqCpBZ2QHhIsr39Mmb2NkN0LQiecYfuzdl4r8RnH/XW/MkkDqfpTxfJcAsIafRXZEuIYF2TCYJxQBTM2l+EMdPqy+mHBCwQlHtxCB3CkeG/XFbzQwQM+bgFNnD2a/EB2LPEKqSZzEYhQ6eA1nTusVmTlo6AASYE1MgalDcgX3cdMIYk30fIAnUEq7kfuHh2SZpUPuv1YmYs2cL+8W2s9/wfjKxFkMWO3B9XTq6Q9ewphJVi+dSmv5l2BJsT3VYrsyp0deC5mCNgRpuTaLx+GcqUWDl4I/fVzq/bQW2Rwq4csC3w14402KEE8M4j8L+B9smYNN7IiplJfms/8B77p0wQCXZ
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: minio

