apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: minio
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgCOKvKfXrCFnbyAX9yeD7jP3cauM8+NJK+xWH4kurY3BlNyyFQfe64a0uwyM8pc6pKrWha/82daiQj04+rHlj3n5TNU1FAJ0egCff+5l8HIScwrJPaU0lpkAtugrPBosoi9Q1ZHRkUemLB6N+iYa6GnNWAFFmuyj7QKUnIRv6oCijwP47Q1edOc4I5dtIvQ6uUu0UFdlXCRUd1sPoFh5bWKLalLQw3XzFpzxBzLNfbf9n9FVxqldlo/9K55K2heB+MXUj6navSMao1S/b3e5RK4XZoqoDGpzXuIRmHnQhvlqidzLbarxffGe9pX50AidHlsokSUvEnCEGRoZHitXz+mJMBnEt0VEz/Ic3La950v+hQNEbIraj2Vp54/dcYBIZ15FspQJIg5dk62ScCuiILvx9rEqEILJOvKQ0fgHOGUtF7gxkoi7G107ESuJN1bmWs+DBn/VhMovHnFCzFNweBhC/VLuLrLMyTBgPzXXN4KFTMd7I4sq8ntm1Vvg/n+fue6iH4AXLQRdTkEBWO3xNgKGUXyrEtrPK7JHTrilkrKaVSi40wERp8eBGIEc4q3TlIK5Z9HVUwMifhx51pER/f4Pa/kJrEaWMUNQ2aihaTM9b+qLlvtQAFVB/8w6x9eaqXxPYDC06j14rL0y03UtrHePSRBRZSp/gC8GY+4SzB8aDCOsnkLzIxWhJDjqM8d5LtdZXfikZHnJRADeqXdSZGEsHCIHutDVPhOKfM1eG/pnKfGdggj9VrXVBcAZwyfUaJ5mGmAB32oDS5cKvwUoWEU
    MINIO_ROOT_USER: AgA10FzTYxNboosM8148/bqYBQpzEHamRRli9jmT/CisTbaGvdBujl0znWmHaP9/9wOZTTDxxAmfXQFc2JLzLDFHl2UUe8Rl1BMwCyS+cBzYZG7AHpxQPkRko1DXGS0IoqY1+4D1pBHpujq1Ya9sN2S0qLxa0ZfaWSbhK1V9W5zp/oXxciwTXGHxSpc0q0CuDULBYAuQ3jO4Iw5yuNHGgs0aXPjMwFCf2N7L/mOxVF2pZi+mLH+9VmKLpCad37cahBRilywcQp2N51mB4i727tc0t4AF+AircMl0JUQL9HPdDXktdd29ycbXPbVfHcBEjd1ohIXNoDN2lAg+hoOkCUKa7AaxvtHdcF1nKG7wXJcqdwPF3PxgBLvuuHbh9ud3JvYI0Zs+ugvINOfcK3HHYxemtPDXAnpnXg86LZLWMuorZtinPLiQFLy9w63WlDc6V5gIcInSDAVM+/C6lzqZtEp5OX65NJVjpGJZl8ijMtHaD/dGCRVaZBiBjB0MbOMaL18I21lQnnZpI711a7/nJw1ZbhbYNB9gJhJZV/nQJG2xvAIw8Imj1loMycMrDCaRXgH4D2BJo0Z3NFR6MHd+b4f/Vnd/O5mPMIsQ/kD6SLLE55KxuoBGZkFHnxkYxUHBQeBxHmN/tJwJC7NqD+jK3X/If/sxkpotM5gaLMhCW3bE49XAkex6Q7fSNKFJODLvgj8yaaDnR1rBqp/I
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: minio

