apiVersion: v1
kind: ConfigMap
metadata:
  name: fail2ban-jails
  namespace: fail2ban
data:
  sshd.conf: |
    [sshd]
    enabled = true
    chain = INPUT
    port = ssh
    filter = sshd[mode=aggressive]
    logpath = /var/log/auth.log
    maxretry = 5
    bantime = 600
