apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  # list of supported config entries: https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
  # language=yaml
  valuesContent: |
    # ports:
    #   web:
    #     redirectTo: websecure
    providers:
      kubernetesIngress:
        allowExternalNameServices: true
      kubernetesCRD:
        allowCrossNamespace: true
        allowExternalNameServices: true
    logs:
      general:
        level: INFO
    metrics:
      prometheus:
        # only router labels are false by default
        addEntryPointsLabels: true
        addRoutersLabels: true
        addServicesLabels: true
