apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: backup-daily
  namespace: longhorn-system
spec:
  cron: "0 0 * * ?"
  task: "backup"
  groups:
  - default
  retain: 7
  concurrency: 1
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: backup-weekly
  namespace: longhorn-system
spec:
  cron: "0 1 ? * 0"
  task: "backup"
  groups:
  - default
  retain: 5
  concurrency: 1
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: backup-monthly
  namespace: longhorn-system
spec:
  cron: "0 2 1 * ?"
  task: "backup"
  groups:
  - default
  retain: 12
  concurrency: 1
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: 4h-snapshot
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: 0 0/4 * * ?
  groups:
    - default
  retain: 12
  task: snapshot
