apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
  - https://raw.githubusercontent.com/longhorn/longhorn/v1.4.0/deploy/longhorn.yaml
  - https://raw.githubusercontent.com/longhorn/longhorn/v1.4.0/deploy/podsecuritypolicy.yaml
  - backups.yaml
  - backup-box.yaml
  - backup-box-aws.yaml
  - storagebox-secret.yaml
  - longhorn-ingress.yaml
patches:
  - path: patch-storageclass.yaml
    target:
      version: v1
      kind: ConfigMap
      name: longhorn-storageclass
      namespace: longhorn-system
  - path: patch-replicacount.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: longhorn-driver-deployer
      namespace: longhorn-system
