apiVersion: v1
kind: Service
metadata:
  namespace: metrics
  name: akprox
spec:
  type: ExternalName
  externalName: ak-outpost-authentik-embedded-outpost.authentik.svc.cluster.local
  ports:
    - port: 9000
      name: web
