apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-nginx
spec:
  selector:
    matchLabels:
      app: foo-nginx
  template:
    metadata:
      labels:
        app: foo-nginx
    spec:
      containers:
        - name: foo-nginx
          image: nginx
