apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-oauth
  namespace: default
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: AgBTSKcL2fzjPXixeSzLieLXy8GgqT/Vi1QNqy1gaIKZQcMpz0F7Lg3OlJNI0h+J9GpT8AS+7/3ZuHWl8/Zrz73tirVFYGBCweA+EyPxtQEtH6RFaUrWw9t/idDhuXm+0xs1hKJndAl5yp9ktjCp1A2fg1LILVNiuVD0nxmPHQvCUiv/Kr9k3sSOAWhuhJUjeydNN2ltduojY9HXqksOh8N5QlqD5U0jw+9nbXtzknkmUoHEu3Cr6sYaLdqWl2LXHpX7t/mcyAmI+c3Lm3RaLxzRaxDaWz3pFeuittmQtg2KPNsMdXrvSt1XDIvUktqnT3K68VYR5hW78LGMMgVSTx/RCXWmfbBZuQBa/8cXhw29FgY0JQ98RFrYzgkfwydXZmMibrLhxJrSaizkSevhegY0Fnta0nG0I57rwhWWzlxe4ZxgDKdpIwYsUGlMJfiqEYfa8UWnnx3KMKW1lTsDwSFQKLSa1pWVZma4KivFVg9w1HTKS5GElZwVKAqThIYnpyOetpoBqRNrdmXBWkyNqs5gDSgudGkgpeqE6aRsuNIFNB67zaLVFDd/3chSLwENpUyuwHmUbwB1BzwByqIIEyty7KrrZHaB2TacLq5XsEJkVBiz9ryE8Of1rjv5AW6I1t5NAjSzYwiV7NlgO25ZmfIGk15N2BIOsZJaiGyo46IZ+fOhRa+gyP0I/IEG6eloi8OE4d/lZMIqqO+GaCHE2rBiRcFaAmuFV9a20lqSEX01fyFEAya5to1e
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgAcHRzajlXOgUoItD/PKi6tJlfuzZBzGhbreTahPw3wqbbHaQfPlJhryO0vTbDI30dQ5JQqZKalC2ivbZTDodgW/qJGxcN6pgM/T+CoM3KoTyE6K9k9FF3PrdmCSDSmiEvqjFnqDy3X52ENsSgOsbq4l/L2wbsFZqlzqARJkTKRUO2A2atfM2NkA60BFZFmmku5/sXJjXswaw1vWtsbMmtrSOgrMaxKJAkup6Rh54rPi86f5lWt2mYnVIDIF6eJco7P1oXrPDxSAZxjK4AM5g3A3P3Ao29QjFl+45mCir5nfpsYrWWkcvWODo8aFF/gedPKLU3lXWUb1wA5UmtdFk+9jlgVhKrrXRaWljHM5MGZV1PySyj82A+epk2AJ0okNCW0Ik/uq6bIe9ri72qtX1oIo4rZmPNfvwUHfTLo3jnkBmPsUV5Ho20pV0CyKRkS9EtooV2XqrSZjKAf5LrJFHlVQYm6DmsXr9xtqXcgTGCxYHlDrk8GqAiI3v5kfJyx1yfrH7XW5kovCL/DoXX685tmNA3g1yRtIBGW3RMh4M8HrR1GfXYwUDUMLJh9L3QcgY+a7s0Vx897zPBA814hpYgRaCyv04XQI2tSw75qCbDTydpbcoPeeJWd7F+VrphbLL0NOg1KKqUXODOiwY5veO1p7Af4x+hRS7A+Z6ikm14mhrBjKRFORnZbxWkZZ9UKzaQ7PCj+ZrhEaBCkytuLZQXKKeDGSfjMuIoQNE/cnSJP5lglDBtCAIQ7eThN6PKFPWxGS2O/q240pkUMJ0FDGMPbiLoDi/g0uAaLMO9WVI7ruFjkyAxeU+HylFPIqrXngw3IIHbPxuB8XgQkE9N9408FJotajb+GQ+W+SHLVXZVpzw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana-oauth
      namespace: default

