apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prometheus-secrets
  namespace: default
spec:
  encryptedData:
    minio-token: AgAR/AqnT2txmV5JTzP+DoBqUu5I/W/qwFPCL14NaXZielYVWxz45OMaEfGHPm9HZBBUBSLQchvpLG6cdW74vqXgbGYfyCxhE/p24y8qReIAEyMMCmk/vpen1IJjukCAHqUoy0A8njD9A/QIp3W0DzINo/FZ0yPP6ZWfXfr4nX/Ie+5j2KEM5UVfZIdGDThBYw7aX95FpAQULp/3zPT8AnUaq80fkrVibluJT81isUHK7nhK8XP2SxJRggtS02+kHUnhnVVKqTALKyHBeCGFFp774X9YApC2T/6TFplxB/84cHSHJlhv0re7Od63wGbPs3iD1dqgPxnHTibvZ0GPN1mGn3jm5q72Z3Ds0LnVCQzCXjhf7SA0d3yybLlq3M6MzOvQ3EQ3DTNFA2Z6L4IQyjcUseUPBP/nulmdd8y/C0kc9rrNq2rpapeCGw/UYVUaqXSaWbdQefWV5cFk7KzK7GRd5ypZkPlQdoKNLJimzliqMvSOMErEN72YMAwuC/XzqNsKZz5AAByyoqtrK41FQ0qwjrJjrdA1NvAlVXKTVvDIw/Ih2O6kdugMu6jno0We0sjTAAnLjN+KQ+r+w6izQvkX+9DPqSTE40TLKv9N3YHE1ZCu0XjfK3Fml27stb6o69vCzFGMQufkQgtyiOJlVDC+pzdE2nT7wHZ4rsqECtPjmdwwvv/rJC8zsu3Q+hS3OxWa4r26VKRBw2rT00vPdt9v1/oTuV5rsAKWNjlWo5DoMZ2AWxWLzg7vBPytcDKgmKQ0fc1eXTwlQuULpIGxWjsUZUm2XeWY5xcFae94d4zrJnNkiUtsyToAYeJ3dTMlxSeee41B9hO+jFIkP4TcaBYW0Ud2jHWRLr+/+/35xzhBPXsO8B4tm64INCMHS27TMT3ja5g2XmKlEDpPbMGB1iQ/In9zo2X60J/k1Cf8iwJa0U9jfeYngoXoLAZyXbIi3ncW1HVI+di/
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: prometheus-secrets
      namespace: default

