apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prometheus-secrets
  namespace: default
spec:
  encryptedData:
    minio-token: AgBW98jlHqaS57pPW2s3ZrcTHEq9NYVER30M3iwOi+Fkw0DzPJWeCDXo4A7Ou0YjEZpBGih6Jz3m1VAtrACCKI0qjUyrpGCKEBO7YLuQzLxaOS+Mor8xoR5c9tMk+mL5DdDp6l/NVKDBdJcbUbG9cQ3KWMiJ48Gj3opkD8RGaqxr7U+m93K42rHByd+AhrU/FTjRs2akijbbk+bS0wBcFr/tBs8tQwe0BdO1fnEdwkxBtzUAMsr2It+vt/ml+f07V06mTTC+SlSYZS2J3Bw1Esfu41Q9GLv2Lv9WXSdx5puRoNLzNcztSmVd5w5owpjkX/dk99ZswHZolty2KoQEpdEDh7ec6TvRU3qwBo/lsr8Trm/+PL5Oh9ZrJuYjwFt0zCSRCfFRTBas+C9iMJPYUQRKR/wW5vN4T+qO2Ix/aBu85IYc9qdy++XrSnXT2dP5SJaHNCrqSZqDQhvWPWTqW2YHoMTKhWBekIpEpcMfjoSyx2H+HpA71VwO8aXYsSA00rdTcNKhcF/vn8LsDETREHZJy1gYkGERCzwa15T9ESAOe7JNXpHF6Wy5HTdZZjE46R+BfVFgs+335RlM20g9M0qFlZn/c54qYEcOekJsdSViRn5CZuHUYXnvS/cf7FxAeACxfU/zXiaqh7io2tIsdkDIGLhpfwrTtaoPVK2GWy19WdoVQOcyjHBXaVkMBs46M9sbIzpP6Vv1wIrYhxuuds/kRqzlWGQFiFnRDASLF/gTo10p5iqvhOD1vW7kGc7CoyES9Tmth+l7WamdtX564XRZ5nmP5/OcpKdqXqLGl9tAtm3rKAoHHcrnXZqCVkiigqa/noxA0oC3alD32OlkKY/Q+mGW+ihoH4ThKqPPVomR9+emU9qtNZ3yLs1M//tj3ph7PA5IOt5XRbsNFTkEk3+zxfNxQri+cnu9ug6k15aCnkFZ4uKaCGXky0CnRDlzPqVytkQEKhvh
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: prometheus-secrets
      namespace: default

