apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: graylog
  namespace: logging
spec:
  encryptedData:
    GRAYLOG_PASSWORD_SECRET: AgALRQNM8UBYBen3ZVJUGw+Vsw6qFssG2Opq1x0+v25NBIVxqB9Uw9b/hjU3BCFv/N7DDI836Y08csUMilnPmpH6t58vwO8yrPgZ0Hnt3YSR2nSi9lSv498A0gBwsuq6h8Yun1RQG4+uARR3FgCJe5uDC5aD8IgzbduBKlsxZc57Od5FsA6Pn/AZ2PzFoW2dLXH0pgUDTRgEejgGOvSJZew2xXPJeJ7j2B4TryFnMrD2IvZa0nhnhJ++FVHtxpj42+b+1NC/RsGKgjkflL982b1EfSHBOcAy6tpW4sJVY10WtHOyga9VkHZkBCHShIEBMP0FaMHPxFS1x36wZGIKCA08yfWrmrVdfjrG1YASBiEbgF369NdwF7X8zYjYJHja0WQHh9JjKScQhkB4klYsPBwbL8/WMo4Ryi4cLa4LDay9X7P0rBdv8sv37/lbe/jR/3hnH68CsEWqxRK7250Y+H3m5N7HJ3tW+qlI00FIemZkySwy03xTrIruZrrNantKO/mMHTcZ61sURtyPREZiEFap+T2YMMBx+qFQn4epwOz9X6e6k8WSqXN1uTB1y1Rx2YaigPl6PPbY1hSVuO3bkA+lXqqKJGkLbhB2/vtZ4xYpG5JcWVgY6200XcuvpvNGW3y/5Mh2RWDyfJqMFjaR+XGXeY5YwMz3lMEuxpBP1oH08HgjuecNF7XkeaR+AIcBhbCGiQYxOzZcCEoLvBVxZaoUIOaEf8fky5RDUpIS1zVOee5NarSuVJxvXmUkYRbtWqN8ktk+i5MmHQ4hQW5X/h8X
    GRAYLOG_ROOT_PASSWORD_SHA2: AgArzJ1nwio1ILiVQU2YnmXnOEy4Qvpg2nvrssdrLOl8KDoLQFkkXy2hgPr2YpuK3lTJusI3vCyFHvgRiMUfrvDa2t2YZm0aDOob+R8iDIG/klC/KQWQbw33Ae/CiF8mGUSrDYp4T+E2cUQOeDVtb6AB/3PFW790bmKemXWqoBDSP/fe5gcjeqab3Mzxp4W0Z2qHYXjWB9ai2FwjCfV0978SkorzHNa7lg56/dghhXQ6P+6hJEWFwmHj58fB4jkcLrLPbgj/ZMNxzDlx3UMonBanS05RmesKJtCoC/dTlVphtr9W0QQ7yt3j8BgfeOWIt5LUX9nf2WXZhfpG1uxq64d7LUgIQjDI4oerHRI7OvJUuFUUAKkrWAb3IdjdtkeLmZ6ThxtlxCtoLfp1ETGbmeg41o8q0TuH8AhXMiQ5qcPrnXF3yU0MVCof2c+pH1yyt8k2ncA++Ws3RU6V2Cr2VOLuVuKQBapPz+IP8tHpaSYpwj5QUMUVBWAHm07I/cG+XnJzozKhJxn2HR4bAR4LxpXOLfVCuUQoQYNH3OlyBSEtCAlaouZQDFNDuE8s6On6KklIC7SGPAurjKkG59uA3IDlHopTmM76deWeo/J1E66/eZOaCjj125d1eaqukF9IQH78SQaDwA9mJLAMzMOlQfv3yJQXInwLo5BVKUql+yXU0GLeMVAuPUlsxS8zZmJqeqI+4oTn19dxM4gq0fCCeT7oLXsBQodnbWFhkGtQSQdjcta14LXuWJ8MMC6rLqVKl2FoA8q1eEcqQrdc4UbEfEQv
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: graylog
      namespace: logging

