apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog
  namespace: logging
  labels:
    app: graylog
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: graylog
  template:
    metadata:
      labels:
        app: graylog
    spec:
      containers:
        - name: graylog
          image: graylog/graylog:4.2
          ports:
            - containerPort: 9000
              name: web
            - containerPort: 12201
              name: gelf
          env:
            - name: GRAYLOG_HTTP_EXTERNAL_URI
              value: https://graylog.771.blue/
            - name: GRAYLOG_MONGODB_URI
              value: mongodb://mongodb/graylog
            - name: GRAYLOG_ELASTICSEARCH_HOSTS
              value: http://elastic:9200
            - name: GRAYLOG_TRUSTED_PROXIES
              value: 10.42.0.0/24
          envFrom:
            - secretRef:
                name: graylog
          # volumeMounts:
          #   - mountPath: /usr/share/graylog/data/journal
          #     name: graylog-data
          #     subPath: journal
          #   - mountPath: /usr/share/graylog/data/config
          #     name: graylog-data
          #     subPath: config
      volumes:
        - name: graylog-data
          persistentVolumeClaim:
            claimName: graylog
---
apiVersion: v1
kind: Service
metadata:
  name: graylog
  namespace: logging
spec:
  selector:
    app: graylog
  ports:
    - port: 9000
      name: web
    - port: 12201
      name: gelf
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: graylog
  namespace: logging
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: authentik-authentik@kubernetescrd
spec:
  rules:
    - host: graylog.jemand771.net
      http:
        paths:
          - backend:
              service:
                name: graylog
                port:
                  name: web
            pathType: Prefix
            path: /
