apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: logging
  labels:
    app: graylog-mongodb
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: graylog-mongodb
  template:
    metadata:
      labels:
        app: graylog-mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.2
          ports:
            - containerPort: 27017
              name: mongodb
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-data
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: graylog-mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: logging
spec:
  selector:
    app: graylog-mongodb
  ports:
    - port: 27017
      name: mongodb
